### ISSUE TITLE
Updated instructions needed for google-assistant-sdk 0.3.x

### ISSUE THREAD

**Issue by saket424** [rgrokett/RaspiAsteriskGoogle#1]
I must compliment you for the very detailed pdf you have drafted to jumpstart the installation of GoogleAssistant and AmazonAlexa.

It appears Google has been changing google-assistant-sdk quite a bit. Your instructions assume version 0.2.x and does not seem to work for 0.3.x . If it is not too much to ask, could you update your docs to show us the new way after the grpc changes and new auth_helpers etc

https://stackoverflow.com/questions/44091251/when-installing-google-assistant-i-an-error-googlesamples-assistant-is-a-p

**Comment by saket424** [comment]
I can confirm that your very detailed instructions work if I revert to google-assistant-sdk version 0.2.1 dated May 11

git clone https://github.com/googlesamples/assistant-sdk-python
cd assistant-sdk-python
git checkout checkout eccd5d799419ca3e4d82e13e7b5c9b74f948c97b
python setup.py build
sudo python setup.py install
cd /usr/local/lib/python2.7/dist-packages/
sudo mv googlesamples googlesamples0.3.2 
sudo cp -a /usr/local/lib/python2.7/dist-packages/google_assistant_sdk-0.2.1-py2.7.egg/googlesamples  /usr/local/lib/python2.7/dist-packages/


Again thanks for all your efforts in documenting this complicated set of steps and making them look seemingly easy

**Comment by rgrokett** [comment]
Updated to support v0.3.2 google assistant sdk.  
Thanks for the heads up.
