### ISSUE TITLE
Asterisk Alexa integration

### ISSUE THREAD

**Issue by steve-beaumont** [rgrokett/RaspiAsteriskGoogle#3]
This caught my eye the other day and thought I might give it a try, however, i believe process described to register with Amazon has changed. I'm having problems when I run the grant_token.sh. I think the problem is arising whilst trying to obtain the YOURTOKEN part detailed in step (following figure 10) in the PDF. Can you help ../Steve

**Comment by rgrokett** [comment]
I assume you mean the RaspiAsteriskAlexa application, not this RaspiAsteriskGoogle one here...  

In the Step. 4 "Copy the URL below to a notepad...."  I assume you edited the URL "YOURCLIENTID" with your Client Id (like **amzn1.application-oa2-client.d49babebc6a54e0f**....)  and "YOURPRODUCTID" with the name you gave at the beginning (like "**MyAsteriskPBX**") (_NOT your Client Secret_)

`https://www.amazon.com/ap/oa?client_id=YOURCLIENTID&scope=alexa%3Aall&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22YOURPRODUCTID%22,%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%2212345%22%7D%7D%7D&response_type=code&redirect_uri=https%3A%2F%2Flocalhost`

Then pasted the URL into a browser window.  You should then get an Amazon login screen for asterisk_alexa where you have to reenter your email/passwd and click Okay.  Then you should get the browser error screen (Step 5) with the **YOURTOKEN** in the address URL. 

These Amazon security tokens are the trickiest part of the entire project!

I have updated the PDF for the Amazon screen changes https://github.com/rgrokett/RaspiAsteriskAlexa

**Comment by steve-beaumont** [comment]
Russel, thanks for your response I've considerably more success this time, however, i'm not quite there yet. The extension answers and prompts for a question after the beep. However, I never get a response. I did a little debugging and have the following from the console.


I can see the tokens and the temporary .sln sound file appearing in /tmp it doesn't seem to clear out the files after a call.


Please note this is Raspbx (Asterisk +FreePBX on a Raspberry Pi)

The sounds files are help in /var/lib/asterisk/sounds/custom and the agi script itself is in /var/lib/asterisk/agi-bin


Again thanks for your help, this is fantastic idea hope you have some success with it.


>>>>>

<SIP/2010-00000008>AGI Tx >> agi_request: alexa.agi
<SIP/2010-00000008>AGI Tx >> agi_channel: SIP/2010-00000008
<SIP/2010-00000008>AGI Tx >> agi_language: en_GB
<SIP/2010-00000008>AGI Tx >> agi_type: SIP
<SIP/2010-00000008>AGI Tx >> agi_uniqueid: 1513884550.8
<SIP/2010-00000008>AGI Tx >> agi_version: 13.12.1
<SIP/2010-00000008>AGI Tx >> agi_callerid: 2010
<SIP/2010-00000008>AGI Tx >> agi_calleridname: 2010
<SIP/2010-00000008>AGI Tx >> agi_callingpres: 1
<SIP/2010-00000008>AGI Tx >> agi_callingani2: 0
<SIP/2010-00000008>AGI Tx >> agi_callington: 0
<SIP/2010-00000008>AGI Tx >> agi_callingtns: 0
<SIP/2010-00000008>AGI Tx >> agi_dnid: *10
<SIP/2010-00000008>AGI Tx >> agi_rdnis: unknown
<SIP/2010-00000008>AGI Tx >> agi_context: from-internal
<SIP/2010-00000008>AGI Tx >> agi_extension: *10
<SIP/2010-00000008>AGI Tx >> agi_priority: 5
<SIP/2010-00000008>AGI Tx >> agi_enhanced: 0.0
<SIP/2010-00000008>AGI Tx >> agi_accountcode:
<SIP/2010-00000008>AGI Tx >> agi_threadid: -1241697248
<SIP/2010-00000008>AGI Tx >> agi_arg_1: en-us
<SIP/2010-00000008>AGI Tx >>
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Starting..."
<SIP/2010-00000008>AGI Tx >> 200 result=0
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Checking channel status."
<SIP/2010-00000008>AGI Tx >> 200 result=0
<SIP/2010-00000008>AGI Rx << CHANNEL STATUS
<SIP/2010-00000008>AGI Tx >> 200 result=6
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Got AVS token."
<SIP/2010-00000008>AGI Tx >> 200 result=0
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: RECORD FILE /tmp/avs_audio3900 sln # -1 BEEP s=2"
<SIP/2010-00000008>AGI Tx >> 200 result=0
<SIP/2010-00000008>AGI Rx << RECORD FILE /tmp/avs_audio3900 sln "#" "-1" BEEP "s=2"
<SIP/2010-00000008>AGI Tx >> 200 result=99981 (timeout) endpos=8160
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Playing /usr/share/asterisk/sounds/en/auth-thankyou"
<SIP/2010-00000008>AGI Tx >> 200 result=0
<SIP/2010-00000008>AGI Rx << STREAM FILE /usr/share/asterisk/sounds/en/auth-thankyou "#"
[2017-12-21 19:29:26] WARNING[3894][C-00000008]: file.c:774 ast_openstream_full: File /usr/share/asterisk/sounds/en/auth-thankyou does not exist in any format
<SIP/2010-00000008>AGI Tx >> 200 result=-1 endpos=0
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Failed to play /usr/share/asterisk/sounds/en/auth-thankyou."
<SIP/2010-00000008>AGI Tx >> 200 result=0
<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Cleaning temp files."
<SIP/2010-00000008>AGI Tx >> 200 result=0

<<<<<






________________________________

**Comment by rgrokett** [comment]
`<SIP/2010-00000008>AGI Rx << NOOP " -- alexa.agi: Failed to play /usr/share/asterisk/sounds/en/auth-thankyou."`

It looks like it cannot find the audio file auth-thankyou.gsm.   I think FreePBX puts audio files in a different place. Did you see the FreePBX changes shown in the bottom of the README.md file:
https://github.com/rgrokett/RaspiAsteriskAlexa/blob/master/README.md

I haven't tried using FreePBX with this, as it not the same as the bare Asterisk.

**Comment by steve-beaumont** [comment]
Russell,


Thanks again. That helped a lot. I put a symbolic to to the location of the 'auth-thankyou.*' files now works 😊


One minor niggle, not sure this is intentional or not, the script leave behind the *.dat files in /tmp after the call has terminated:-


Contenets of /tmp following call termination:-


>>>>>>>>>>>>

-rw-r--r--  1 asterisk asterisk 127322 Dec 22 13:15 avs_audio20064.dat
-rw-r--r--  1 asterisk asterisk 102362 Dec 22 13:16 avs_audio20082.dat
-rw-r--r--  1 asterisk asterisk 225882 Dec 22 13:35 avs_audio20370.dat
-rw-r--r--  1 asterisk asterisk 241242 Dec 22 13:36 avs_audio20386.dat
-rw-r--r--  1 asterisk asterisk 705882 Dec 22 13:36 avs_audio20394.dat
-rw-r--r--  1 asterisk asterisk  33242 Dec 22 13:37 avs_audio20418.dat
-rw-r--r--  1 asterisk asterisk  33242 Dec 22 13:38 avs_audio20425.dat
-rw-r--r--  1 asterisk asterisk 110682 Dec 22 13:38 avs_audio20440.dat
-rw-r--r--  1 asterisk asterisk    807 Dec 22 13:38 request.dat
-rw-r--r--  1 asterisk asterisk   8499 Dec 22 13:38 response.dat
-rw-r--r--  1 asterisk asterisk    567 Dec 22 13:37 token.avs
-rw-r--r--  1 asterisk asterisk    815 Dec 22 13:37 token.req
-rw-r--r--  1 asterisk asterisk   1190 Dec 22 13:37 token.resp
<<<<<<<<<<<<<<<

I really must get some Christmas shopping done 😊


Steve

________________________________
